name: Build and Push Multiple Images

on:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - variant: latest
            version: 1.0.0
          - variant: bun
            version: 1.2.10
          - variant: node
            version: 23.11.0
          - variant: php
            version: 8.4.6
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Docker Hub Registry
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          push: true
          file: ./src/${{ matrix.variant }}/Dockerfile
          platforms: linux/amd64,linux/arm64
          build-args: |
            VARIANT=${{ matrix.variant }}
            VERSION=${{ matrix.version }}
          tags: |
            ${{ vars.DOCKERHUB_USERNAME }}/devbox:${{ matrix.variant }}
            ${{ vars.DOCKERHUB_USERNAME }}/devbox:${{ matrix.variant }}-${{ matrix.version }}
